name: 'Composite action'

runs:
  using: "composite"
  steps:
    - run: echo "Running composite action"
      shell: bash
    - uses: action/checkout@v3
      repository: guan-kevin/javascript-action
      ref: version-test
      path: version-test
    - run: cd version-test && git log -1
      shell: bash
#     - run: |
#         echo "Exit 1"
#         exit 1
#       shell: bash
#     - run: |
#         print("ERROR IF YOU CAN SEE THIS LINE")
#       shell: python
