name: 'Composite action'

runs:
  using: "composite"
  steps:
    - run: echo "Running composite action"
      shell: bash
    - uses: actions/checkout@v3
      with:
        repository: guan-kevin/javascript-action
        ref: version-test
        path: version-test
    - run: cd version-test && git log -1
      shell: bash
    - uses: actions/checkout@v3
      with:
        repository: guan-kevin/hunting-ground5.0
        ref: main
        path: xyz
    - run: cd xyz && git log -1
      shell: bash
#     - run: |
#         echo "Exit 1"
#         exit 1
#       shell: bash
#     - run: |
#         print("ERROR IF YOU CAN SEE THIS LINE")
#       shell: python
