runs:
  using: "composite"
  steps:
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - run: |
        echo "actor: ${{ github.actor }}"
        echo "ref: ${{ github.ref }}"
        echo "triggering_actor: ${{ github.triggering_actor }}"
        echo "workflow: ${{ github.workflow }}"
        echo "head_ref: ${{ github.head_ref }}"
        echo "base_ref: ${{ github.base_ref }}"
        echo "event_name: ${{ github.event_name }}"
        echo "action: ${{ github.action }}"
        echo "action_repository: ${{ github.action_repository }}"
        echo "action_ref: ${{ github.action_ref }}"
        echo "action_path: ${{ github.action_path }}"
        echo "action_status: ${{ github.action_status }}"
        echo "workspace: ${{ github.workspace }}"
       shell: bash
    - run: |
        echo "Second step in setup_jsk composite action"
        echo "PWD:"
        pwd
      shell: bash
