inputs:
  your-name:
    description: 'Your name?'
    required: false
    default: unknown
  repoName:
    description: 'Repo name?'
    required: true
  action_name:
    description: 'Action name?'
    default: empty
  STEPNAME:
    description: 'Step name?'
    required: true
    default: EMPTY

runs:
  using: "composite"
  steps:
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - run: |
        echo "Second step in setup_jsk composite action"
        echo "PWD:"
        pwd
      shell: bash
    - run: |
        echo "Your name is ${{ inputs.YOUR-NAME }}"
        echo "Repo name is ${{ inputs.REPONAME }}"
        echo "Action name is ${{ inputs.ACTION_NAME }}"
        echo "Step name is ${{ inputs.STEPNAME }}"
        printenv
      shell: bash
    - run: |
        echo "actor: ${{ github.actor }}"
        echo "ref: ${{ github.ref }}"
        echo "triggering_actor: ${{ github.triggering_actor }}"
        echo "workflow: ${{ github.workflow }}"
        echo "head_ref: ${{ github.head_ref }}"
        echo "base_ref: ${{ github.base_ref }}"
        echo "event_name: ${{ github.event_name }}"
        echo "action: ${{ github.action }}"
        echo "action_repository: ${{ github.action_repository }}"
        echo "action_ref: ${{ github.action_ref }}"
        echo "action_path: ${{ github.action_path }}"
        echo "action_status: ${{ github.action_status }}"
        echo "workspace: ${{ github.workspace }}"
      shell: bash
