runs:
  using: "composite"
  steps:
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - run: |
        echo "Second step in setup_jsk composite action"
        echo "PWD:"
        pwd
      shell: bash
 
