runs:
  using: "composite"
  steps:
    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - run: exit 2
      shell: bash
    - run: printenv
      shell: bash
 
