
name: Test Cache Action
on: [push, pull_request]
  
jobs:
  build:
    name: Cache test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          cache: 'pip'
      - name: Python command
        run: python src/pitching_machine.py
