name: Test Checkout Action
on: [push, pull_request]
  
jobs:
  build:
    name: Checkout test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Checkout another directory
        uses: actions/checkout@v3
        with:
          repository: BugSwarm/bugswarm
          path: bugswarm
      - name: List contents in direction
        run: ls && ls bugswarm
      - name: Python command
        run: python src/pitching_machine.py
