name: Test Checkout Action
on: [push, pull_request]
  
jobs:
  build:
    name: Checkout test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Checkout another directory
        uses: actions/checkout@v2
        with:
          repository: guan-kevin/hunting-ground5.0
          submodules: true
          path: abc
      - name: List contents in directory
        run: ls abc
      - name: List again
        run: |
          cd abc
          git log -1
      - name: One more time
        run: |
          cd abc/hunting-ground
          ls
          git log -1
      - name: Checkout javascript-action
        uses: ./composite_action
      - name: Checkout another directory AGAIN
        uses: actions/checkout@v3
        with:
          repository: guan-kevin/hunting-ground5.0
          path: test1
      - name: Check version again
        run: cd test1 && git log -1
      - name: Python command
        run: python src/pitching_machine.py
