on: [push, pull_request]
name: GitHub Context Testing

env:
  WorkflowEnv: Workflow level

jobs:
  build:
    name: Test Action
    runs-on: ubuntu-20.04
    env:
      JobEnv: Job Level
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
      - run: |
          echo "actor: ${{ github.actor }}"
          echo "ref: ${{ github.ref }}"
          echo "triggering_actor: ${{ github.triggering_actor }}"
          echo "workflow: ${{ github.workflow }}"
          echo "head_ref: ${{ github.head_ref }}"
          echo "base_ref: ${{ github.base_ref }}"
          echo "event_name: ${{ github.event_name }}"
          echo "action: ${{ github.action }}"
          echo "action_repository: ${{ github.action_repository }}"
          echo "action_ref: ${{ github.action_ref }}"
          echo "action_path: ${{ github.action_path }}"
          echo "action_status: ${{ github.action_status }}"
          echo "workspace: ${{ github.workspace }}"
      - name: Setup Java then pwd and print contexts
        uses: ./.github/setup_jdk
      - name: Run another composite action
        uses: guan-kevin/composite-action@v8
        env:
          StepEnv: Step Level
      - run: python src/pitching_machine.py
