name: Main
on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: self-hosted
    container: $${{matrix.container}}
    strategy:
      matrix:
        container:
          - ubuntu:latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Run shell script
        run: |
          echo 'Hello world'
          ls -al

