name: Main
on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: self-hosted
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - ubuntu:latest
          - ubuntu:bionic
          - ubuntu:xenial
  
    steps:
      - uses: actions/checkout@v2
      - name: Run shell script
        run: |
          echo 'Hello world'
          ls -al
      - name: Install dependencies for Python
        run: |
          apt update
          apt install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7' 
      - name: Run python script
        run: |
          python src/pitching_machine.py

