name: Main
on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-18.04
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - bugswarm/images:ubuntu-16.04
          - bugswarm/images:ubuntu-18.04
          - bugswarm/images:ubuntu-20.04
  
    steps:
      - uses: actions/checkout@v2
      - name: Run shell script
        run: |
          echo 'Hello world'
          ls -al
          echo 'Skip step to avoid bug'
          exit 255
#      - name: Run python script
#        working-directory: ./src
#        run: |
#          python3 pitching_machine.py
#      - name: Link with flake8
#        run: |
#          pip3 install flake8==3.7.9
#          flake8 src/pitching_machine.py
  build_number_2:
    name: Second build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        fruit: [apple, pear]
        animal: [cat, dog]
        include:
          - color: green
          - color: pink
            animal: cat
          - fruit: apple
            shape: circle
          - fruit: banana
          - fruit: banana
            animal: cat
    steps:
      - name: Run shell script
        run: |
          echo 'Hello world'
          echo 'From ${{ matrix.fruit }}'
