name: Main
on: [push, pull_request]

env:
  TEST: "TEST_ENV"
  DEBUG: "DEBUG_ENV"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
#       - name: Run shell script
#         run: |
#           echo 'Hello world'
#           ls -al
      - name: Run Random script
        run: |
          python src/pitching_machine.py
#           echo "RANDOM=$RANDOM"
#         env:
#           PYTHON_TEST: "PYTHON_TEST_ENV"
#           ABC: ABC
#           ABC2: A'BC'
#           ABC3: A' BC
#           RANDOM: random string with spaces in it
#           NOT-RANDOM: "not-random string with spaces in it"
#           XYZ: X"Y"Z
#           WXYZ: W \"X\" \"Y" 'Z
      - name: Run bash script
        run: |
          echo "Running bash script"
          echo "Random number: $RANDOM"
          echo "TEST: $TEST and DEBUG: $DEBUG and LOCAL: $LOCAL"
          echo "Print out X is hello:"
          X=hello
          
          if [[ $X == "hello" ]]; then
          	echo "X is hello"
          else
          	echo "X is not hello"
          fi
        env:
          LOCAL: This is a random string
      - name: Run python script
        run: |
          import os
          import random
          print('Running python script')
          print('Random number: {}'.format(random.randomint(1, 10000))
          print('TEST: {} and DEBUG: {} and LOCAL: {}'.format(os.getenv('TEST'), os.getenv('DEBUG'), os.getenv('LOCAL'))
          print('Print out X is hello:')
          X = 'hello'
          
          if X == 'hello':
            print('X is hello')
          else:
            print('X is not hello')
      
          
