name: Main
on: [push, pull_request]

env:
  TEST: "TEST_ENV"
  DEBUG: "DEBUG_ENV"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: List files
        run: |
          ls -lia
      - name: Run Random script
        run: |
          python src/pitching_machine.py
        env:
          PYTHON_TEST: "PYTHON_TEST_ENV"
          ABC: ABC
          ABC2: A'BC'
          ABC3: A' BC
          RANDOM: random string with spaces in it
          NOT-RANDOM: "not-random string with spaces in it"
          XYZ: X"Y"Z
          WXYZ: W \"X\" \"Y" 'Z
      - name: Run bash script
        run: |
          echo "Running bash script"
          echo "Random number: $RANDOM"
          echo "TEST: $TEST and DEBUG: $DEBUG and LOCAL: $LOCAL"
          echo "Print out X is hello:"
          X=hello
          
          if [[ $X == "hello" ]]; then
          	echo "X is hello"
          else
          	echo "X is not hello"
          fi
        env:
          LOCAL: This is a random string
      - name: Run python script
        run: |
          import os
          import random
          print('Running python script')
          print('Random number: {}'.format(random.randint(1, 10000)))
          print('TEST: {} and DEBUG: {} and LOCAL: {}'.format(os.getenv('TEST'), os.getenv('DEBUG'), os.getenv('LOCAL')))
          print('Print out X is hello:')
          X = 'hello'
          
          if X == 'hello':
            print('X is hello')
          else:
            print('X is not hello')
        env:
          LOCAL: This is a random string
        shell: python
      - name: Print file
        run: |
          cat hello.txt
        working-directory: ./src/texts
      - name: Print file again
        run: |
          ls -lia
          cat src/texts/hello.txt
#   hello:
#     name: Hello World
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python 
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.6'
#       - name: Run Random script
#         run: python src/pitching_machine.py
#       - name: Hello world action step
#         id: hello
#         uses: guan-kevin/javascript-action@v1
#         with:
#           who-to-greet: 'guan-kevin'
#       - name: Bye world action step
#         id: bye
#         uses: guan-kevin/javascript-action@v2
#         with:
#           who-to-greet: 'guan-kevin'
#       - name: Hello world action step
#         id: hello2
#         uses: guan-kevin/javascript-action@v3
#         with:
#           who-to-greet: 'guan-kevin'
#       - name: Hello world action step
#         id: hello3
#         uses: guan-kevin/javascript-action@v4-beta
#         with:
#           who-to-greet: 'guan-kevin'
#       - name: Hello world action step
#         id: hello4
#         uses: guan-kevin/javascript-action@61ad9be6642213e4aefc1aceed54fd7374ae874e
#         with:
#           who-to-greet: 'guan-kevin'

  hello:
    name: Hello World
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Run Random script
        run: python src/pitching_machine.py
      - name: Step 1
        uses: guan-kevin/javascript-action@v7
        with:
          who-to-greet: 'guan-kevin'
      - name: Step 2
        uses: guan-kevin/javascript-action/hello@v7
        with:
          who-to-greet: 'guan-kevin'
      - name: Step 3
        uses: guan-kevin/javascript-action/hello/again@v7
        with:
          who-to-greet: 'guan-kevin'
      - name: Step 4
        uses: guan-kevin/javascript-action/bye@v7
        with:
          who-to-greet: 'guan-kevin'
      - name: Step 5
        uses: guan-kevin/javascript-action/bye/again@v7
        with:
          who-to-greet: 'guan-kevin'
      - name: Step 6
        uses: guan-kevin/javascript-action/test/@v7
        with:
          who-to-greet: 'guan-kevin'

