name: Main
on: [push, pull_request]

env:
  TEST: "TEST_ENV"
  DEBUG: "DEBUG_ENV"
  WorkflowEnv1: Workflow 1
  WorkflowEnv2: Workflow 2
  WorkflowJobEnv: Workflow 3
  WorkflowJobStepEnv: Workflow 4
  WorkflowStepEnv: Workflow 5

jobs:
  build:
    name: ENV test
    runs-on: ubuntu-20.04
    env:
      JobEnv1: Job 1
      JobEnv2: Job 2
      WorkflowJobEnv: Job 3
      WorkflowJobStepEnv: Job 4
      JobStepEnv: Job 5
    defaults:
      run:
        shell: python
        working-directory: src/scripts
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Python 1
        run: python ../pitching_machine.py
        shell: bash
      - name: Python 2
        run: python run.py
        shell: bash
      - name: Bash 1
        run: |
          chmod u+x run.sh
          ./run.sh
        shell: bash
      - name: Python 3
        run: |
          import os
          import random
          print('Running python script')
          print('Random number: {}'.format(random.randint(1, 10000)))
          print('TEST: {} and DEBUG: {} and LOCAL: {}'.format(os.getenv('TEST'), os.getenv('DEBUG'), os.getenv('LOCAL')))
      - name: Python 4
        run: pwd && ls && python run.py
        shell: bash
        working-directory: .
      - name: Print Env
        run: |
          echo "WorkflowEnv1: {$WorkflowEnv1}"
          echo "WorkflowEnv2: {$WorkflowEnv2}"
          echo "JobEnv1: {$JobEnv1}"
          echo "JobEnv2: {$JobEnv2}"
          echo "StepEnv1: {$StepEnv1}"
          echo "StepEnv2: {$StepEnv2}"
          echo "WorkflowJobEnv: {$WorkflowJobEnv}"
          echo "JobStepEnv: {$JobStepEnv}"
          echo "WorkflowJobStepEnv: {$WorkflowJobStepEnv}"
          echo "WorkflowStepEnv: {$WorkflowStepEnv}"
        shell: bash
        env:
          StepEnv1: Step 1
          StepEnv2: Step 2
          WorkflowJobStepEnv: Step 3
          JobStepEnv: Step 4
          WorkflowStepEnv: Step 5
      - name: Print GitHub Env
        shell: bash
        run: |
          echo "${CI}"
          echo "${GITHUB_ACTION}"
          echo "${GITHUB_ACTION_PATH}"
          echo "${GITHUB_ACTION_REPOSITORY}"
          echo "${GITHUB_ACTIONS}"
          echo "${GITHUB_ACTOR}"
          echo "${GITHUB_API_URL}"
          echo "${GITHUB_BASE_REF}"
          echo "${GITHUB_ENV}"
          echo "${GITHUB_EVENT_NAME}"
          echo "${GITHUB_EVENT_PATH}"
          echo "${GITHUB_GRAPHQL_URL}"
          echo "${GITHUB_HEAD_REF}"
          echo "${GITHUB_JOB}"
          echo "${GITHUB_PATH}"
          echo "${GITHUB_REF}"
          echo "${GITHUB_REF_NAME}"
          echo "${GITHUB_REF_PROTECTED}"
          echo "${GITHUB_REF_TYPE}"
          echo "${GITHUB_REPOSITORY}"
          echo "${GITHUB_REPOSITORY_OWNER}"
          echo "${GITHUB_RETENTION_DAYS}"
          echo "${GITHUB_RUN_ATTEMPT}"
          echo "${GITHUB_RUN_ID}"
          echo "${GITHUB_RUN_NUMBER}"
          echo "${GITHUB_SERVER_URL}"
          echo "${GITHUB_SHA}"
          echo "${GITHUB_STEP_SUMMARY}"
          echo "${GITHUB_WORKFLOW}"
          echo "${GITHUB_WORKSPACE}"
          echo "${RUNNER_ARCH}"
          echo "${RUNNER_DEBUG}"
          echo "${RUNNER_NAME}"
          echo "${RUNNER_OS}"
          echo "${RUNNER_TEMP}"
          echo "${RUNNER_TOOL_CACHE}"
          

# jobs:
#   build:
#     name: Build and test
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python 
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.6'
#       - name: List files
#         run: |
#           ls -lia
#       - name: Run Random script
#         run: |
#           python src/::
#         env:
#           PYTHON_TEST: "PYTHON_TEST_ENV"
#           ABC: ABC
#           ABC2: A'BC'
#           ABC3: A' BC
#           RANDOM: random string with spaces in it
#           NOT-RANDOM: "not-random string with spaces in it"
#           XYZ: X"Y"Z
#           WXYZ: W \"X\" \"Y" 'Z
#       - name: Run bash script
#         run: |
#           echo "Running bash script"
#           echo "Random number: $RANDOM"
#           echo "TEST: $TEST and DEBUG: $DEBUG and LOCAL: $LOCAL"
#           echo "Print out X is hello:"
#           X=hello
          
#           if [[ $X == "hello" ]]; then
#           	echo "X is hello"
#           else
#           	echo "X is not hello"
#           fi
#         env:
#           LOCAL: This is a random string
#       - name: Run python script
#         run: |
#           import os
#           import random
#           print('Running python script')
#           print('Random number: {}'.format(random.randint(1, 10000)))
#           print('TEST: {} and DEBUG: {} and LOCAL: {}'.format(os.getenv('TEST'), os.getenv('DEBUG'), os.getenv('LOCAL')))
#           print('Print out X is hello:')
#           X = 'hello'
          
#           if X == 'hello':
#             print('X is hello')
#           else:
#             print('X is not hello')
#         env:
#           LOCAL: This is a random string
#         shell: python
#       - name: Print file
#         run: |
#           cat hello.txt
#         working-directory: ./src/texts
#       - name: Print file again
#         run: |
#           ls -lia
#           cat src/texts/hello.txt
#   hello:
#     name: Hello World
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python 
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.6'
#       - name: Run Random script
#         run: python src/pitching_machine.py
#       - name: Hello world action step
#         id: hello
#         uses: guan-kevin/javascript-action@v1
#         with:
#           who-to-greet: 'guan-kevin'
#       - name: Bye world action step
#         id: bye
#         uses: guan-kevin/javascript-action@v2
#         with:
#           who-to-greet: 'guan-kevin'
#       - name: Hello world action step
#         id: hello2
#         uses: guan-kevin/javascript-action@v3
#         with:
#           who-to-greet: 'guan-kevin'
#       - name: Hello world action step
#         id: hello3
#         uses: guan-kevin/javascript-action@v4-beta
#         with:
#           who-to-greet: 'guan-kevin'
#       - name: Hello world action step
#         id: hello4
#         uses: guan-kevin/javascript-action@61ad9be6642213e4aefc1aceed54fd7374ae874e
#         with:
#           who-to-greet: 'guan-kevin'

#   hello:
#     name: Hello World
#     runs-on: ubuntu-20.04
#     steps:
#       - uses: actions/checkout@v2
#       - name: Set up Python 
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.6'
#       - name: Run Random script
#         run: python src/pitching_machine.py
#       - name: Step 1
#         uses: guan-kevin/javascript-action@v7
#         with:
#           who-to-greet: 'guan-kevin'
#       - name: Step 2
#         uses: guan-kevin/javascript-action/hello@v7
#         with:
#           who-to-greet: 'guan-kevin'
#       - name: Step 3
#         uses: guan-kevin/javascript-action/hello/again@v7
#         with:
#           who-to-greet: 'guan-kevin'
#       - name: Step 4
#         uses: guan-kevin/javascript-action/bye@v7
#         with:
#           who-to-greet: 'guan-kevin'
#       - name: Step 5
#         uses: guan-kevin/javascript-action/bye/again@v7
#         with:
#           who-to-greet: 'guan-kevin'
#       - name: Step 6
#         uses: guan-kevin/javascript-action/test/@v7
#         with:
#           who-to-greet: 'guan-kevin'

