name: Main
on: [push, pull_request]

env:
  TEST: "TEST_ENV"
  DEBUG: "DEBUG_ENV"

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Run shell script
        run: |
          echo 'Hello world'
          ls -al
      - name: Run python script
        run: |
          python src/pitching_machine.py
        env:
          PYTHON_TEST: "PYTHON_TEST_ENV"
