name: Main
on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: self-hosted
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        container:
          - ghcr.io/catthehacker/ubuntu:act-16.04
          - ghcr.io/catthehacker/ubuntu:act-18.04
          - ghcr.io/catthehacker/ubuntu:act-20.04
  
    steps:
      - uses: actions/checkout@v2
      - name: Run shell script
        run: |
          echo 'Hello world'
          ls -al
      - name: Set up glibc6
        run: |
          sudo apt update
          sudo apt install glibc6
      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Run python script
        run: |
          python src/pitching_machine.py
      - name: Link with flake8
        run: |
          pip install flake8==3.7.9
          flake8 src/pitching_machine.py

